package movieapp.persistence;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

import javax.persistence.EntityManager;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.NullSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;

import movieapp.entity.Movie;

@DataJpaTest
class MovieRepositoryTest {

	@Autowired
	private MovieRepository movieRepository;
	
	@Autowired
	private EntityManager entityManager;
	
	@Test
	void testFindByTitle() {
		//given
		// 1 - a title of movies to read in the test
		String title = "The man who knew too Much";
		// 2 - writing data in database via the entitymanager
		var moviesDataBase = List.of(
				new Movie(title, 1934, null),
				new Movie(title, 1956, null),
				new Movie("The Man Whoo Knew Too Little", 1997, null));
		//ask to each movie of the list movies to apply persist method from entityManager
		moviesDataBase.forEach(entityManager::persist); // persist method >> SQL : insert for each movie
		entityManager.flush();
		//when : read from the repository
		var moviesFound = movieRepository.findByTitle(title);
		//then
		assertAll(
				() -> assertEquals(2, moviesFound.size()),
				() -> assertEquals(title, moviesFound.get(0).getTitle())
				);
		assertAll(moviesFound.stream().map(
				m -> () -> assertEquals(title, m.getTitle(), "title")
				));
//		for (Movie m: moviesFound) {
//			assertEquals(title, m.getTitle(), "title");
//		}
	}
	
	@ParameterizedTest
	@ValueSource(strings = {
			"Z", 
			"Blade Runner", 
			"Night of the Day of the Dawn of the Son of the Bride of the Return of the Revenge of the Terror of the Attack of the Evil Mutant Hellbound Flesh Eating Crawling Alien Zombified Subhumanoid Living Dead, Part 5"})
	void testSaveTitle(String title) {
		// given
		int year = 1982;
		int duration = 173;
		// when + then
		saveAssertMovie(title, year, duration);
	}
	

	@Test
	void testSaveTitleEmptyNOK() {
		String title = null;
		int year = 1982;
		int duration = 173;
		assertThrows(DataIntegrityViolationException.class, 
				() -> saveAssertMovie(title, year, duration));
	}
	
	
	@ParameterizedTest
	@ValueSource(ints = { 1888, 1982, Integer.MAX_VALUE })
	void testSaveYear(int year) {
		// given
		String title = "Blade Runner";
		int duration = 173;
		// when + then
		saveAssertMovie(title, year, duration);
	}
	
	@Test
	void testSaveYearNullNOK() {
		String title = "Blade runner";
		Integer year = null;
		int duration = 173;
		assertThrows(DataIntegrityViolationException.class, 
				() -> saveAssertMovie(title, year, duration));
	}
	
	@ParameterizedTest
	@ValueSource(ints = { 1888, 1982, Integer.MAX_VALUE })
	@NullSource
	void testSaveDuration(Integer duration) {
		// given
		String title = "Blade Runner";
		int year = 1982;
		// when + then
		saveAssertMovie(title, year, duration);
	}
	

	private void saveAssertMovie(String title, Integer year, Integer duration) {
		Movie movie = new Movie(title, year, duration);
		// when
		movieRepository.save(movie);
		// then
		var idMovie = movie.getId();
		assertNotNull(idMovie, "id generated by database");
//		var optMovieFromRepo = movieRepository.findById(idMovie);
//		System.out.println(optMovieFromRepo);
//		var movieFromRepo = optMovieFromRepo.get();
//		assertEquals(movie, movieFromRepo);
		// NB : following test only checks that object read is the same as object written (cache)
		movieRepository.findById(idMovie)
			.ifPresent(m -> assertEquals(movie, m));
		// debug purpose only
		//System.out.println(movie);
	}

}
